### ISSUE TITLE
Error 422

### ISSUE THREAD

**Issue by tomasbjerre** [tomasbjerre/violation-comments-to-github-lib#1]
CHECKSTYLE INFO com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck src/main/java/se/bjurr/violations/lib/example/MyClass.java 19 
JSHINT WARN  web/js-file.js 6 
File: "web/js-file.js"Line: "6"Comment: "Reporter: JSHINT
Rule: ?
Severity: WARN
File: ../../../web/js-file.js L6

Use &apos;===&apos; to compare with &apos;null&apos;.: if (a == null)

<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>
"
org.eclipse.egit.github.core.client.RequestException: Validation Failed (422): Invalid value for 'path' field
    at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
    at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643)
    at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
    at org.eclipse.egit.github.core.service.PullRequestService.createComment(PullRequestService.java:488)
    at se.bjurr.violations.comments.github.lib.GitHubCommentsProvider.createSingleFileComment(GitHubCommentsProvider.java:123)
    at se.bjurr.violations.comments.lib.CommentsCreator.createSingleFileComments(CommentsCreator.java:70)
    at se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:46)

**Comment by tomasbjerre** [comment]
curl -H "Authorization: token XXXXXXXXXXXXXX" -X POST --data '{"body": "the body 2", "commit_id": "f0859607dd53ca7f5ad58c7c773f31212ca50557", "position": 1, "path": "web/js-file.js"}' https://api.github.com/repos/tomasbjerre/violations-test/pulls/2/comments

**Comment by tomasbjerre** [comment]
Also comments are failing sometimes:
curl -H "Authorization: token XXXXXXX" -X POST --data '{"body": "test comment 123", "commit_id": "f0859607dd53ca7f5ad58c7c773f31212ca50557", "position": 22, "path": "src/main/java/se/bjurr/violations/lib/example/MyClass.java"}' https://api.github.com/repos/tomasbjerre/violations-test/pulls/2/comments

**Comment by tomasbjerre** [comment]
was
